include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    avoid_web_libraries_in_flutter: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    require_trailing_commas: true
    sort_unnamed_constructors_first: true
    library_private_types_in_public_api: false
