name: mobx_reminder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  flutter_hooks: ^0.20.2
  cloud_firestore: ^4.9.3
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
